import pathlib

import av
import numpy as np
import pytest

from fava import VideoHandler

_SKIP_UNSORTED_PTS = pytest.mark.skip(reason="unsorted PTS / infinite-loop bug not fixed in this PR")

# All (codec, extension) combinations generated by generate_numbered_video.py.
# libx265 is skipped: its DTS != PTS ordering is not handled yet (follow-up PR).
CODEC_EXTENSION_COMBOS = [
    pytest.param(("mpeg4", "mp4"),   id="mpeg4_mp4"),
    pytest.param(("libx264", "mp4"), id="libx264_mp4"),
    pytest.param(("libx264", "mkv"), id="libx264_mkv"),
    pytest.param(("mpeg4", "avi"),   id="mpeg4_avi"),
    pytest.param(("vp9", "webm"),    id="vp9_webm"),
    pytest.param(("libx265", "mp4"), id="libx265_mp4"),
]


@pytest.fixture()
def video_info(request):
    codec, extension = request.param
    video = pathlib.Path(__file__).parent / f"test_video/numbered_video_{codec}.{extension}"

    frame_pts = []
    keyframe_pts = []
    frame_array = []
    with av.open(str(video)) as container:
        stream = container.streams.video[0]
        stream.codec_context.skip_frame = "NONE"  # decode all frames

        for frame in container.decode(stream):
            frame_pts.append(frame.pts)
            frame_array.append(frame.to_ndarray())
            if frame.key_frame:
                keyframe_pts.append(frame.pts)

    return np.stack(frame_array), frame_pts, keyframe_pts, video


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
@pytest.mark.parametrize(
    "requested_frame_ts, expected_frame_id",
    [(0, 0), (0.1, 0), (1.0, 1), (1.1, 1), (1.6, 1), (99, 99), (99.6, 99), (111, 99)],
)
def test_video_handler(video_info, requested_frame_ts, expected_frame_id):
    _, frame_pts_ref, _, video = video_info
    with VideoHandler(video, time=np.arange(100)) as handler:
        frame = handler.get(requested_frame_ts)
        expected_pts = frame_pts_ref[expected_frame_id]
        assert frame.pts == expected_pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_single_index_return_frame(video_info):
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 7
        frame = video[idx]
        assert isinstance(frame, av.VideoFrame), "Single frame should be a single frame"
        np.testing.assert_array_equal(frame.to_ndarray(), frame_array[idx])


@pytest.mark.parametrize(
    "start, stop, step",
    [
        (0, 5, 1),      # simple forward slice
        (10, 20, 2),    # skip frames
        (25, None, 3),  # slice to end with step
        (None, 10, 1),  # from beginning
        (None, None, 5),  # full range with step
    ],
)
@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_slice_return_frame(video_info, start, stop, step):
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = slice(start, stop, step)
        frames = video[idx]

        start_idx = start or 0
        stop_idx = stop if stop is not None else video.shape[0]
        step_val = step or 1
        expected_len = len(range(start_idx, stop_idx, step_val))

        assert isinstance(frames, list), "Sliced result should be a list of frames"
        assert all(
            isinstance(f, av.VideoFrame) for f in frames
        ), "Sliced result should be a list of av.VideoFrame"
        assert len(frames) == expected_len, f"Expected {expected_len} frames but got {len(frames)}"
        frame_array_handler = np.stack([f.to_ndarray() for f in frames])
        np.testing.assert_array_equal(frame_array_handler, frame_array[slice(start, stop, step)])


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_video_shape(video_info):
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 7
        frame = video[idx].to_ndarray(format="rgb24")
        assert frame.shape == (video.shape[2], video.shape[1], 3)

@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_pts_ordering(video_info):
    # pts from full decoding
    _, frame_pts, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        video._wait_for_index(15)
        np.testing.assert_array_equal(video.all_pts, np.sort(video.all_pts))
        np.testing.assert_array_equal(video.all_pts, np.asarray(frame_pts, dtype=video.all_pts.dtype))


# ---------------------------------------------------------------------------
# Buffer integration tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_get_populates_buffer(video_info):
    """A frame decoded via get() should land in the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        video.get(5.0)
        idx = VideoHandler._ts_to_index(5.0, video.time)
        assert idx in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_get_hits_buffer_on_second_call(video_info):
    """Second get() for the same timestamp must return the cached frame
    without re-decoding — proved by closing the container between calls."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        first = video.get(5.0)

        # Close the underlying container so any attempt to decode would raise.
        video.container.close()
        video.container = None

        # Should succeed from the buffer, not touch the container.
        second = video.get(5.0)

    assert first.pts == second.pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_int_populates_buffer(video_info):
    """video[idx] (integer index) routes through get(), so the frame should
    end up in the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 10
        video[idx]
        assert idx in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_int_hits_buffer_on_second_call(video_info):
    """video[idx] called twice: second call must come from the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 10
        first = video[idx]

        video.container.close()
        video.container = None

        second = video[idx]

    assert first.pts == second.pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_buffer_fifo_eviction_in_handler(video_info):
    """Accessing more than buffer_size distinct frames evicts the earliest one."""
    _, _, _, video_path = video_info
    buf_size = 5
    with VideoHandler(video_path, time=np.arange(100), buffer_size=buf_size) as video:
        # warm up: access buf_size + 1 distinct frames (skip 0; __init__ decodes it)
        for i in range(1, buf_size + 2):
            video[i]

        # frame at index 1 was inserted first and should have been evicted
        assert 1 not in video._buffer
        # the most recent buf_size frames must still be present
        for i in range(2, buf_size + 2):
            assert i in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
@pytest.mark.parametrize(
    "start, stop, step",
    [
        (0, 5, 1),
        (10, 20, 2),
        (95, 100, 1),
        (99, 100, 1),
        (0, 100, 25),
    ],
)
def test_getitem_slice_matches_expected(video_info, start, stop, step):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # captured immediately after __init__ to see thread state before any slice call
        print(f"\n[diag] {video.name}  [{start}:{stop}:{step}]"
              f"  _n_frames={video_obj._n_frames}  _i={video_obj._i}"
              f"  len(time)={len(video_obj.time)}  index_ready={video_obj._index_ready.is_set()}")
        raw_frames = list(video_obj[start:stop:step])
        print(f"[diag] post-slice: n_collected={len(raw_frames)}"
              f"  _n_frames={video_obj._n_frames}  _i={video_obj._i}"
              f"  index_ready={video_obj._index_ready.is_set()}")
        frames = np.stack([f.to_ndarray() for f in raw_frames])
        video_obj._wait_for_index()
        np.testing.assert_array_equal(
            frame_array[start:stop:step], frames
        )

@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_decoupled_current_frame_and_pts_decoding_via_get(video_info):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # this populates the buffer
        _ = video_obj[10]
        _ = video_obj[11]
        # move backwards current frame (pick from buffer, should not move decoder head)
        _ = video_obj[10]
        # make sure the pts of stream is different
        assert video_obj.current_frame.pts != video_obj._stream_pts
        # make sure that
        frame = video_obj[12]
        np.testing.assert_array_equal(frame_array[12], frame.to_ndarray())


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_decoupled_current_frame_and_pts_decoding_via_decode_multiple(video_info):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # this populates the buffer
        _ = video_obj[10:12]
        # move backwards current frame (pick from buffer, should not move decoder head)
        _ = video_obj[10]
        # make sure the pts of stream is different
        assert video_obj.current_frame.pts != video_obj._stream_pts
        # make sure that
        frames = video_obj[12:14]
        frames = np.stack([f.to_ndarray() for f in frames])
        np.testing.assert_array_equal(frame_array[12:14], frames)