import asyncio
import concurrent.futures
import pathlib

import av
import numpy as np
import pytest

from asyncvideo import VideoHandler

_SKIP_UNSORTED_PTS = pytest.mark.skip(
    reason="unsorted PTS / infinite-loop bug not fixed in this PR"
)

# All (codec, extension) combinations generated by generate_numbered_video.py.
# libx265 is skipped: its DTS != PTS ordering is not handled yet (follow-up PR).
CODEC_EXTENSION_COMBOS = [
    pytest.param(("mpeg4", "mp4"), id="mpeg4_mp4"),
    pytest.param(("libx264", "mp4"), id="libx264_mp4"),
    pytest.param(("libx264", "mkv"), id="libx264_mkv"),
    pytest.param(("mpeg4", "avi"), id="mpeg4_avi"),
    pytest.param(("vp9", "webm"), id="vp9_webm"),
    pytest.param(("libx265", "mp4"), id="libx265_mp4"),
]


@pytest.fixture()
def video_info(request):
    codec, extension = request.param
    video = (
        pathlib.Path(__file__).parent / f"test_video/numbered_video_{codec}.{extension}"
    )

    frame_pts = []
    keyframe_pts = []
    frame_array = []
    with av.open(str(video)) as container:
        stream = container.streams.video[0]
        stream.codec_context.skip_frame = "NONE"  # decode all frames

        for frame in container.decode(stream):
            frame_pts.append(frame.pts)
            frame_array.append(frame.to_ndarray())
            if frame.key_frame:
                keyframe_pts.append(frame.pts)

    return np.stack(frame_array), frame_pts, keyframe_pts, video


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
@pytest.mark.parametrize(
    "requested_frame_ts, expected_frame_id",
    [(0, 0), (0.1, 0), (1.0, 1), (1.1, 1), (1.6, 1), (99, 99), (99.6, 99), (111, 99)],
)
def test_video_handler(video_info, requested_frame_ts, expected_frame_id):
    _, frame_pts_ref, _, video = video_info
    with VideoHandler(video, time=np.arange(100)) as handler:
        frame = handler.get(requested_frame_ts)
        expected_pts = frame_pts_ref[expected_frame_id]
        assert frame.pts == expected_pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_single_index_return_frame(video_info):
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 7
        frame = video[idx]
        assert isinstance(frame, av.VideoFrame), "Single frame should be a single frame"
        np.testing.assert_array_equal(frame.to_ndarray(), frame_array[idx])


@pytest.mark.parametrize(
    "start, stop, step",
    [
        (0, 5, 1),  # simple forward slice
        (10, 20, 2),  # skip frames
        (25, None, 3),  # slice to end with step
        (None, 10, 1),  # from beginning
        (None, None, 5),  # full range with step
    ],
)
@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_slice_return_frame(video_info, start, stop, step):
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = slice(start, stop, step)
        frames = video[idx]

        start_idx = start or 0
        stop_idx = stop if stop is not None else video.shape[0]
        step_val = step or 1
        expected_len = len(range(start_idx, stop_idx, step_val))

        assert isinstance(frames, list), "Sliced result should be a list of frames"
        assert all(isinstance(f, av.VideoFrame) for f in frames), (
            "Sliced result should be a list of av.VideoFrame"
        )
        assert len(frames) == expected_len, (
            f"Expected {expected_len} frames but got {len(frames)}"
        )
        frame_array_handler = np.stack([f.to_ndarray() for f in frames])
        np.testing.assert_array_equal(
            frame_array_handler, frame_array[slice(start, stop, step)]
        )


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_video_shape_native(video_info):
    """With pixel_format=None, shape reports the native to_ndarray() layout."""
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        assert video.shape == frame_array.shape


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
@pytest.mark.parametrize("pixel_format", ["rgb24", "yuv420p", "yuv444p"])
def test_video_shape_matches_returned_array(video_info, pixel_format):
    """shape[1:] is the shape of the array a single index returns."""
    _, _, _, video_path = video_info
    with VideoHandler(
        video_path, time=np.arange(100), pixel_format=pixel_format
    ) as video:
        frame = video[7]
        assert video.shape == (len(video), *frame.shape)


# ---------------------------------------------------------------------------
# Interleaving and concurrency
#
# Addressing a frame by number and by timestamp used to be switched by a flag on
# a class-level ``threading.local``, shared by every handler that existed. These
# tests pin the property that replaced it: the method you call decides how the
# argument is read, so nothing is shared and interleaved or concurrent readers
# cannot contaminate one another.
#
# Note what is deliberately *not* asserted: a single handler is not safe for
# concurrent use. ``get`` mutates the buffer, the last-decoded index and the
# stream position, and seeks the container -- two threads sharing one handler
# would interleave those. Each test below gives every worker its own handler,
# which is also what ``AsyncVideoReader`` does with a process per video.
# ---------------------------------------------------------------------------

# one codec is enough here: these test shared state, not container handling
_ONE_CODEC = [CODEC_EXTENSION_COMBOS[1]]  # libx264/mp4


@pytest.mark.parametrize("video_info", _ONE_CODEC, indirect=True)
def test_get_and_getitem_agree(video_info):
    """The two ways of addressing a frame must return the same frame.

    This is the guarantee the flag existed to provide, now provided by ``get``
    and ``__getitem__`` sharing ``_get_by_index``.
    """
    frame_array, _, _, video_path = video_info
    times = np.arange(100, dtype=float)
    with VideoHandler(video_path, time=times) as video:
        for idx in (0, 1, 7, 42, 99):
            by_index = video[idx]
            by_time = video.get(times[idx])
            np.testing.assert_array_equal(by_index.to_ndarray(), frame_array[idx])
            np.testing.assert_array_equal(by_time.to_ndarray(), frame_array[idx])


@pytest.mark.parametrize("video_info", _ONE_CODEC, indirect=True)
def test_two_handlers_interleaved_in_one_thread(video_info):
    """Alternating between two handlers must not let one affect the other.

    The old flag lived on the class, so a handler reading by index could change
    how another handler in the same thread read its argument.
    """
    frame_array, _, _, video_path = video_info
    times = np.arange(100, dtype=float)
    with (
        VideoHandler(video_path, time=times) as a,
        VideoHandler(video_path, time=times) as b,
    ):
        for idx in (5, 20, 60, 90):
            # a reads by index, b reads the same frame by timestamp, alternating
            np.testing.assert_array_equal(a[idx].to_ndarray(), frame_array[idx])
            np.testing.assert_array_equal(
                b.get(times[idx]).to_ndarray(), frame_array[idx]
            )
            # and back the other way round
            np.testing.assert_array_equal(
                a.get(times[idx]).to_ndarray(), frame_array[idx]
            )
            np.testing.assert_array_equal(b[idx].to_ndarray(), frame_array[idx])


@pytest.mark.parametrize("video_info", _ONE_CODEC, indirect=True)
def test_handlers_in_separate_threads(video_info):
    """Handlers used concurrently from different threads stay independent."""
    frame_array, _, _, video_path = video_info
    times = np.arange(100, dtype=float)
    indices = [3, 17, 44, 71, 98]

    def read_all(by_time: bool):
        # one handler per worker, opened inside the thread
        with VideoHandler(video_path, time=times) as video:
            out = []
            for idx in indices:
                frame = video.get(times[idx]) if by_time else video[idx]
                out.append(frame.to_ndarray())
            return out

    # half the workers address frames by time, half by index, all at once
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        futures = [pool.submit(read_all, i % 2 == 0) for i in range(4)]
        results = [f.result(timeout=120) for f in futures]

    for frames in results:
        for idx, frame in zip(indices, frames):
            np.testing.assert_array_equal(frame, frame_array[idx])


@pytest.mark.parametrize("video_info", _ONE_CODEC, indirect=True)
def test_handlers_in_concurrent_async_tasks(video_info):
    """Two tasks on one event loop, interleaved, must not contaminate each other.

    This is the case ``threading.local`` could not have isolated: coroutines on a
    single thread share thread-local state, so a flag set by one task would have
    been visible to the other while it was suspended.
    """
    frame_array, _, _, video_path = video_info
    times = np.arange(100, dtype=float)
    indices = [2, 33, 64, 95]

    async def read(by_time: bool):
        with VideoHandler(video_path, time=times) as video:
            out = []
            for idx in indices:
                frame = video.get(times[idx]) if by_time else video[idx]
                out.append(frame.to_ndarray())
                await asyncio.sleep(0)  # hand control to the other task
            return out

    async def main():
        return await asyncio.gather(read(True), read(False))

    by_time, by_index = asyncio.run(main())
    for idx, (t_frame, i_frame) in zip(indices, zip(by_time, by_index)):
        np.testing.assert_array_equal(t_frame, frame_array[idx])
        np.testing.assert_array_equal(i_frame, frame_array[idx])


# ---------------------------------------------------------------------------
# Frame times
#
# ``time`` is resolved once, by the index thread, and published through a
# future: a frame's timestamp is not knowable until every PTS has been seen, so
# reading it blocks rather than returning a provisional guess.
# ---------------------------------------------------------------------------


@pytest.fixture()
def variable_rate_video():
    """A video whose frames are unevenly spaced in time.

    Generated with explicit per-frame timestamps alternating 20 ms and 60 ms
    gaps, so no single frame rate reproduces them.
    """
    path = (
        pathlib.Path(__file__).parent / "test_video" / "variable_rate_video_libx264.mp4"
    )
    if not path.exists():
        pytest.skip(f"{path} missing — run 'nox -s video_gen' to generate test videos")
    return path


def test_time_is_not_a_uniform_grid(variable_rate_video):
    """On a variable rate video, time must follow the real frame spacing.

    This is the test the constant-rate fixtures cannot provide: there, PTS and a
    uniform grid coincide exactly, so a reader inventing timestamps from the
    nominal rate would pass. Here the nominal rate implies one gap and the actual
    frames have two, so only real timestamps match.
    """
    from generate_numbered_video import variable_frame_intervals

    with VideoHandler(variable_rate_video) as video:
        times = video.time

        gaps = np.round(np.diff(times), 6)
        assert set(gaps.tolist()) == {0.02, 0.06}, "frame spacing must not be uniform"
        np.testing.assert_allclose(
            times, variable_frame_intervals(len(times)), atol=1e-6
        )

        # and the uniform grid the nominal rate would give does *not* match,
        # which is what makes the assertion above meaningful
        uniform = np.linspace(times[0], times[-1], len(times))
        assert not np.allclose(times, uniform, atol=1e-3)


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_time_matches_presentation_timestamps(video_info):
    """Without a provided array, time is the stream's own PTS, in seconds.

    The oracle is an independent decode: the fixture's ``frame_pts`` come from
    PyAV directly, and the time base is read from a separate container, so
    nothing here is derived from the object under test.

    Note this cannot distinguish PTS-derived times from a uniform grid on these
    fixtures -- they are constant rate and start at 0, so both agree exactly. It
    does pin the scaling, the ordering and the length.
    """
    _, frame_pts, _, video_path = video_info
    with av.open(str(video_path)) as container:
        time_base = float(container.streams.video[0].time_base)
    expected = np.asarray(frame_pts, dtype=np.int64) * time_base

    with VideoHandler(video_path) as video:
        np.testing.assert_array_equal(video.time, expected)
        assert len(video.time) == video.shape[0]
        assert np.all(np.diff(video.time) > 0), "frame times must increase"


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_provided_time_is_returned_unchanged(video_info):
    """A correctly sized time array is handed back as given, not resampled."""
    _, _, _, video_path = video_info
    # deliberately uneven, so any resampling to a uniform grid would show up
    provided = np.cumsum(np.linspace(0.01, 0.05, 100)) + 410.0
    with VideoHandler(video_path, time=provided) as video:
        np.testing.assert_array_equal(video.time, provided)


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_provided_time_wrong_length_raises(video_info):
    """A mismatched time array must be rejected, eagerly where possible.

    Containers that declare a frame count are checked at construction, so the
    error lands on the line that passed the array. Containers that declare
    nothing (vp9/webm reports 0) can only be checked once the indexer has
    counted the frames, so there the error surfaces on first use.
    """
    _, _, _, video_path = video_info
    with av.open(str(video_path)) as container:
        declared = container.streams.video[0].frames

    wrong = np.arange(90)  # every fixture video has 100 frames

    if declared > 0:
        with pytest.raises(ValueError, match="one timestamp per frame"):
            VideoHandler(video_path, time=wrong)
    else:
        video = VideoHandler(video_path, time=wrong)
        try:
            # indexing by frame number never consults time, so it still works
            assert video[7] is not None
            with pytest.raises(ValueError, match="one timestamp per frame"):
                video.time  # noqa: B018 - ruff is dumb, this actually raises
        finally:
            video.close()


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_indexing_by_frame_never_waits_on_time(video_info):
    """Frame-number access must not touch ``time``.

    ``__init__`` decodes frame 0 while its own index thread is still running, so
    if the decode path consulted ``time`` it would wait on a future that only
    that thread can resolve -- a deadlock. Substituting a future that never
    resolves proves the decode path is independent of it.
    """
    _, _, _, video_path = video_info
    with VideoHandler(video_path) as video:
        from concurrent.futures import Future

        video._time_future = Future()  # never resolved
        assert video[7] is not None
        assert video[0:3] is not None
        assert video.shape[0] == 100


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_pts_ordering(video_info):
    # pts from full decoding
    _, frame_pts, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        video._wait_for_index(15)
        np.testing.assert_array_equal(video.all_pts, np.sort(video.all_pts))
        np.testing.assert_array_equal(
            video.all_pts, np.asarray(frame_pts, dtype=video.all_pts.dtype)
        )


# ---------------------------------------------------------------------------
# End-of-stream handling
#
# Reading straight through to the last frame exhausts the decoder. On B-frame
# codecs (H.264/H.265) packets arrive in decode order, so reaching a frame near
# the end means consuming the whole stream; the decoder is then flushed and
# raises EOFError on the next packet unless it is re-seeked first. These tests
# cover plain forward playback, which the rest of the suite never does -- it
# reads scattered indices and slices, and so missed this entirely.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_sequential_playthrough(video_info):
    """Every frame, in order, must decode and match an independent decode."""
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        for idx in range(video.shape[0]):
            frame = video[idx]
            np.testing.assert_array_equal(
                frame.to_ndarray(),
                frame_array[idx],
                err_msg=f"frame {idx} differs from the reference decode",
            )


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_playthrough_then_wraps_to_start(video_info):
    """Looping playback: a full pass must not poison the next read."""
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        for idx in range(video.shape[0]):
            video[idx]
        # the request that used to raise EOFError
        np.testing.assert_array_equal(video[0].to_ndarray(), frame_array[0])
        np.testing.assert_array_equal(video[1].to_ndarray(), frame_array[1])


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_reads_after_eof_recover(video_info):
    """Once the stream has hit EOF, reads in any direction must still work."""
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        last = video.shape[0] - 1

        # drive the decoder through the whole stream
        for idx in range(video.shape[0]):
            video[idx]

        for idx in (last, 50, last, 0, last):
            np.testing.assert_array_equal(
                video[idx].to_ndarray(),
                frame_array[idx],
                err_msg=f"frame {idx} wrong after EOF recovery",
            )


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_seek_clears_eof_flag(video_info):
    """A seek flushes the decoder, so it must also clear the EOF flag.

    Set the flag directly rather than by playing to the end: whether a given
    read exhausts the stream depends on the codec's packet ordering, but the
    invariant being checked here -- seeking makes the decoder usable again --
    does not.
    """
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        target_pts, _use_time = video._get_target_frame_pts(0)

        video._at_eof = True
        video._seek(target_pts)
        assert not video._at_eof

        # and the reader is genuinely usable afterwards
        np.testing.assert_array_equal(video[0].to_ndarray(), frame_array[0])


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_stale_eof_flag_still_reads_correctly(video_info):
    """A set EOF flag forces a re-seek, which must not change what is returned.

    Note this does not reproduce the EOF bug -- the decoder here is healthy and
    only the flag is set, so it passes with or without the recovery logic. What
    it pins is that the extra seek the flag triggers is harmless: the read still
    lands on the right frame rather than on the keyframe before it.
    """
    frame_array, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        video[10]
        video._at_eof = True
        np.testing.assert_array_equal(video[11].to_ndarray(), frame_array[11])


# ---------------------------------------------------------------------------
# Buffer integration tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_get_populates_buffer(video_info):
    """A frame decoded via get() should land in the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        video.get(5.0)
        idx = VideoHandler._ts_to_index(5.0, video.time)
        assert idx in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_get_hits_buffer_on_second_call(video_info):
    """Second get() for the same timestamp must return the cached frame
    without re-decoding — proved by closing the container between calls."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        first = video.get(5.0)

        # Close the underlying container so any attempt to decode would raise.
        video.container.close()
        video.container = None

        # Should succeed from the buffer, not touch the container.
        second = video.get(5.0)

    assert first.pts == second.pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_int_populates_buffer(video_info):
    """video[idx] (integer index) routes through get(), so the frame should
    end up in the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 10
        video[idx]
        assert idx in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_int_hits_buffer_on_second_call(video_info):
    """video[idx] called twice: second call must come from the buffer."""
    _, _, _, video_path = video_info
    with VideoHandler(video_path, time=np.arange(100)) as video:
        idx = 10
        first = video[idx]

        video.container.close()
        video.container = None

        second = video[idx]

    assert first.pts == second.pts


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_buffer_fifo_eviction_in_handler(video_info):
    """Accessing more than buffer_size distinct frames evicts the earliest one."""
    _, _, _, video_path = video_info
    buf_size = 5
    with VideoHandler(video_path, time=np.arange(100), buffer_size=buf_size) as video:
        # warm up: access buf_size + 1 distinct frames (skip 0; __init__ decodes it)
        for i in range(1, buf_size + 2):
            video[i]

        # frame at index 1 was inserted first and should have been evicted
        assert 1 not in video._buffer
        # the most recent buf_size frames must still be present
        for i in range(2, buf_size + 2):
            assert i in video._buffer


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
@pytest.mark.parametrize(
    "start, stop, step",
    [
        (0, 5, 1),
        (10, 20, 2),
        (95, 100, 1),
        (99, 100, 1),
        (0, 100, 25),
    ],
)
def test_getitem_slice_matches_expected(video_info, start, stop, step):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # captured immediately after __init__ to see thread state before any slice call
        print(
            f"\n[diag] {video.name}  [{start}:{stop}:{step}]"
            f"  _n_frames={video_obj._n_frames}  _i={video_obj._i}"
            f"  len(time)={len(video_obj.time)}  index_ready={video_obj._index_ready.is_set()}"
        )
        raw_frames = list(video_obj[start:stop:step])
        print(
            f"[diag] post-slice: n_collected={len(raw_frames)}"
            f"  _n_frames={video_obj._n_frames}  _i={video_obj._i}"
            f"  index_ready={video_obj._index_ready.is_set()}"
        )
        frames = np.stack([f.to_ndarray() for f in raw_frames])
        video_obj._wait_for_index()
        np.testing.assert_array_equal(frame_array[start:stop:step], frames)


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_decoupled_current_frame_and_pts_decoding_via_get(video_info):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # this populates the buffer
        _ = video_obj[10]
        _ = video_obj[11]
        # move backwards current frame (pick from buffer, should not move decoder head)
        _ = video_obj[10]
        # make sure the pts of stream is different
        assert video_obj.current_frame.pts != video_obj._stream_pts
        # make sure that
        frame = video_obj[12]
        np.testing.assert_array_equal(frame_array[12], frame.to_ndarray())


@pytest.mark.parametrize("video_info", CODEC_EXTENSION_COMBOS, indirect=True)
def test_getitem_decoupled_current_frame_and_pts_decoding_via_decode_multiple(
    video_info,
):
    frame_array, _, _, video = video_info
    video = pathlib.Path(video)
    with VideoHandler(video) as video_obj:
        # this populates the buffer
        _ = video_obj[10:12]
        # move backwards current frame (pick from buffer, should not move decoder head)
        _ = video_obj[10]
        # make sure the pts of stream is different
        assert video_obj.current_frame.pts != video_obj._stream_pts
        # make sure that
        frames = video_obj[12:14]
        frames = np.stack([f.to_ndarray() for f in frames])
        np.testing.assert_array_equal(frame_array[12:14], frames)
